root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/main cmd/server/main.go"
bin = "tmp/main"
full_bin = "./tmp/main"
include_ext = ["go"]
exclude_dir = ["tmp", "vendor", "tmp-frontend"]
delay = 1000 # ms
stop_on_error = true
log = "air.log"

[log]
time = true

[color]
main = "yellow"
watcher = "cyan"
build = "green"
runner = "magenta"

[misc]
clean_on_exit = true 