# Configures a PostgreSQL container for local development
version: "3.8"
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: exchange_user
      POSTGRES_PASSWORD: exchange_pass
      POSTGRES_DB: exchange_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: 